name: "Upload zip-archive"
on:
  release:
    types: [published]

jobs:
  zip-archive:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.6
        with:
          submodules: true
      - name: Create zip including submodules
        run: |
          cd ..
          zip ${{ github.event.repository.name }}/${{ github.event.repository.name }}-${{ github.ref_name }}.zip ${{ github.event.repository.name }} -r
      - name: Upload zip to release
        uses: softprops/action-gh-release@fb2d03176f42a1f0dd433ca263f314051d3edd44
        with:
          files: |
            ${{ github.event.repository.name }}-${{ github.ref_name }}.zip