name: Generate sources

on:
  workflow_dispatch:

jobs:
  generate-sources:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.0.2
        with:
          submodules: true
      - uses: actions/setup-python@v3
        with:
          python-version: '3.x'
          architecture: 'x64'
      - uses: BSFishy/pip-action@v1
        with:
          packages: |
            pipreqs
            pipx
      - run: ls -a
      - run: cd resources/node && pipx install . 
      - run: pipreqs resources
      - uses: BSFishy/pip-action@v1
        with:
          requirements: resources/requirements.txt
      - name: Create cargo sources
        run: |
          python resources/flatpak-cargo-generator.py src-tauri/Cargo.lock -o cargo-sources.json
      - run: rm -r resources/
      - run: ls -a
      - name: Create node sources
        run: |
          flatpak-node-generator npm -r package-lock.json -o node-sources.json
      - run: ls -a
      - name: Upload PR Info
        uses: actions/upload-artifact@v3.0.1
        with:
          name: node-sources.json
          path: node-sources.json
          retention-days: 10
      - name: Upload PR Info
        uses: actions/upload-artifact@v3.0.1
        with:
          name: cargo-sources.json
          path: cargo-sources.json
          retention-days: 10